spring.application.name=ach-validation


spring.datasource.url=jdbc:postgresql://localhost:5440/karpay
spring.datasource.username=karpay
spring.datasource.password=karpay123

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.sql.init.mode=never
spring.sql.init.platform=postgres
spring.jpa.defer-datasource-initialization=true

# --- Resilience4j
resilience4j.circuitbreaker.instances.achService.sliding-window-size=5
resilience4j.circuitbreaker.instances.achService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.achService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.achService.permitted-number-of-calls-in-half-open-state=2

# --- Resilience4j
resilience4j.retry.instances.achService.max-attempts=3
resilience4j.retry.instances.achService.wait-duration=500ms

# --- JWT ---
jwt.secret=karpay-super-secret-key-change-me-in-production-1234567890
jwt.expiration=3600000